-- Run once in phpMyAdmin before using the DTR Shifts tab.
CREATE TABLE IF NOT EXISTS DTRShiftTemplates (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  timeIn TIME NOT NULL,
  timeOut TIME NOT NULL,
  amBreakMinutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  mealBreakStart TIME NULL,
  mealBreakEnd TIME NULL,
  pmBreakMinutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  breakMinutes SMALLINT UNSIGNED NOT NULL DEFAULT 60,
  graceMinutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  standardMinutes SMALLINT UNSIGNED NOT NULL DEFAULT 480,
  color VARCHAR(20) NOT NULL DEFAULT '#0d6efd',
  active TINYINT(1) NOT NULL DEFAULT 1,
  createdBy INT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dtr_shift_name (name),
  CONSTRAINT fk_dtr_shift_created_by
    FOREIGN KEY (createdBy) REFERENCES employee(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
